### ISSUE TITLE
Document example spack packages.yaml

### ISSUE THREAD

**Issue by adammoody** [LLNL/scr#259]
To help spack users, let's document the lines one might want to add to their ``packages.yaml`` to get a working SCR install.  SCR has direct or indirect dependencies on software that people usually do not install with spack but instead register their existing system-installed packages with spack.  This includes MPI libs, resource managers, and tools like pdsh and libyogrt.  Some of those like system-installed packages like compilers and MPI libs will already be familiar to typical spack users, but others like slurm, pdsh, and libyogrt are probably more specific to SCR.

In our spack install instructions, let's help users by listing examples on how to register those packages, e.g.,
```
slurm:
    externals:
    - spec: slurm
      prefix: /usr
libyogrt:
    externals:
    - spec: libyogrt
      prefix: /usr
```
